"""Update Item model (nullable fields, drop unique barcode)

Revision ID: 00350a3b3bda
Revises: 4c92900c1eda
Create Date: 2025-07-13 14:29:42.135019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00350a3b3bda'
down_revision: Union[str, None] = '4c92900c1eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_barcode', table_name='items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_items_barcode', 'items', ['barcode'], unique=True)
    # ### end Alembic commands ###
