"""Add quantity to items table

Revision ID: 728dc6d808ad
Revises: b23ad7801518
Create Date: 2025-06-30 23:06:10.078153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728dc6d808ad'
down_revision: Union[str, None] = 'b23ad7801518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('ategory_id', sa.Integer(), nullable=True))
    op.drop_constraint('items_category_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'categories', ['ategory_id'], ['id'], ondelete='SET NULL')
    op.drop_column('items', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_category_id_fkey', 'items', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('items', 'ategory_id')
    op.drop_column('items', 'quantity')
    # ### end Alembic commands ###
