"""Fix category_id column name

Revision ID: 9e33f441d98f
Revises: 728dc6d808ad
Create Date: 2025-06-30 23:09:48.348411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e33f441d98f'
down_revision: Union[str, None] = '728dc6d808ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('items_ategory_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('items', 'ategory_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('ategory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_ategory_id_fkey', 'items', 'categories', ['ategory_id'], ['id'], ondelete='SET NULL')
    op.drop_column('items', 'category_id')
    # ### end Alembic commands ###
