"""Add shared_inventory table

Revision ID: c5d068bfca0a
Revises: f44606400419
Create Date: 2025-07-02 19:09:22.634209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d068bfca0a'
down_revision: Union[str, None] = 'f44606400419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'inventory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'inventory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
