"""Add inventory relationship to items

Revision ID: f44606400419
Revises: 9e33f441d98f
Create Date: 2025-07-02 08:55:35.169590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44606400419'
down_revision: Union[str, None] = '9e33f441d98f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventories_id', 'inventories', ['id'], unique=False)
    op.create_index('ix_inventories_name', 'inventories', ['name'], unique=False)
    op.add_column('items', sa.Column('inventory_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('items_owner_id_fkey'), 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'inventories', ['inventory_id'], ['id'], ondelete='CASCADE')
    op.drop_column('items', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(op.f('items_owner_id_fkey'), 'items', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_column('items', 'inventory_id')
    op.drop_index('ix_inventories_name', table_name='inventories')
    op.drop_index('ix_inventories_id', table_name='inventories')
    op.drop_table('inventories')
    # ### end Alembic commands ###
